services:
  backend:
    build: ./backend
    ports:
      - "80:8000"  # Puerto 80 para acceso público
    environment:
      - SECRET_KEY=tu-secret-key-super-segura-para-produccion-2025
      - ENVIRONMENT=production
    restart: unless-stopped
    volumes:
      - ./backend:/app