services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=tu-secret-key-super-segura-para-mvp
    restart: unless-stopped