services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: mi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${BACKEND_IMAGE}
    env_file:
      - .env
    environment:
      DJANGO_ALLOWED_HOSTS: ${DOMAIN}
      POSTGRES_DB: mi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - django_static_volume:/vol/django_static
    depends_on:
      - db
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  caddy:
    image: caddy:2
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - django_static_volume:/vol/django_static:ro
      - frontend_static_volume:/vol/frontend_static:ro
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
    name: db_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  django_static_volume:
    name: django_static_volume
  frontend_static_volume:
    name: frontend_static_volume