openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0

components:
  schemas:
    # 1️⃣ Entidad simple con id
    User:
      type: object
      properties:
        id: { type: integer }
        username: { type: string, maxLength: 150 }
        email: { type: string, maxLength: 255 }
      required: [id, username, email]

    # 2️⃣ Entidad con FK y camelCase
    Profile:
      type: object
      properties:
        id: { type: integer }
        userId:
          type: integer
          description: FK hacia User
          x-foreign-key: User.id
        fullName: { type: string, maxLength: 200 }
        age: { type: integer }
      required: [id, userId, fullName]

    # 3️⃣ Entidad con boolean y number
    Product:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        price: { type: number }
        isAvailable: { type: boolean }
      required: [id, name, price, isAvailable]

    # 4️⃣ Input → debe ignorarse
    ProductInput:
      type: object
      properties:
        name: { type: string }
        price: { type: number }
        isAvailable: { type: boolean }
      required: [name, price, isAvailable]

    # 5️⃣ Error → debe ignorarse
    Error:
      type: object
      properties:
        type: { type: string }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
      required: [type, title, status, detail]
