name: Cleanup Projects Compose and Git EC2

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup EC2 (Docker + Repo)
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            PROJECT_NAME=$(basename "${{ github.repository }}")
            REPO_DIR="/home/${{ secrets.EC2_USER }}/$PROJECT_NAME"

            echo ">>> Deteniendo y eliminando todos los contenedores"
            docker ps -aq | xargs -r docker stop
            docker ps -aq | xargs -r docker rm -f

            echo ">>> Eliminando todas las imágenes"
            docker images -aq | xargs -r docker rmi -f

            echo ">>> Eliminando todos los volúmenes"
            docker volume ls -q | xargs -r docker volume rm -f

            echo ">>> Eliminando todas las redes personalizadas"
            docker network ls --filter type=custom -q | xargs -r docker network rm

            echo ">>> Limpiando system prune por si queda algo"
            docker system prune -af --volumes || true

            echo ">>> Eliminando repositorio clonado en $REPO_DIR"
            rm -rf "$REPO_DIR"

            echo ">>> Cleanup completado."
